[package]
name = "learn-splatoon"
version = "0.0.1"
authors = ["Zageron <hello@adambryant.ca>"]
edition = "2021"


[dependencies]
actix-web = "3.3.2"
env_logger = "0.9.0"
handlebars = { version = "4.1.5", features = ["dir_source"] }
maplit = "1.0.2"
