[package]
name = "learn-splatoon"
version = "0.0.1"
authors = ["Zageron <hello@adambryant.ca>"]
edition = "2021"


[dependencies]
actix-files = "0.6.0-beta.9"
actix-http = "3.0.0-beta.13"
actix-identity = "0.4.0-beta.4"
actix-service = "2.0.1"
actix-web = "4.0.0-beta.12"
env_logger = "0.9.0"
handlebars = { version = "4.1.5", features = ["dir_source"] }
maplit = "1.0.2"
mime = "0.3.16"
mongodb = "2.1.0-beta"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
